apiVersion: v1
kind: Service
metadata:
  name: my-first-app-service
spec:
  type: NodePort
  selector:
    app: my-first-app
  ports:
    - port: 8000      
      targetPort: 8000  
      nodePort: 30080  
